### ISSUE TITLE
print help if invoked w/o parameters OR any of the required parameters is missing

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#1]
currently if the file is invoked w/o any parameters it gives a bit scary stack trace.
<name of current python file> should be replaced with actual name of the py file invoked, the other < > printed exactly. It should print nice help, smth like:

Usage:
<name of current python file> \
   --prevStat <file with previous release statistics> \
   --curStat <file with current release statistics> \
   --outputFile <path to write resulting output to>

**Comment by Cherryhz** [comment]
Solved by adding parser.print_help().
