### ISSUE TITLE
call close on workbook when running file w/o arguments

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#2]
Currently, if the file is invoked w/o arguments, python prints a warning:
Exception: Exception caught in workbook destructor. Explicit close() may be required for workbook.
it might be a good idea to invoke "close()" properly (exception handling?)

**Comment by Cherryhz** [comment]
This should be solved after printing help if file is invoked w/o arguments. I'll leave it open just in case.

**Comment by Cherryhz** [comment]
Now print help when no arguments or number of arguments is not what is expected (3). len(sys.argv) = 7 counted the name of script, the three arguments and their inputs.
