### ISSUE TITLE
Compare sheet: do not merge legend cutoff values with their explanations

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#27]
At the moment in the legend being produced cells with cutoff values and cutoff explanations are merged:
"increase:  5%" is a merged cell.
Please make these 2 cells be un-merged. The rationale behind this is that the cutoff values will be used for conditional formatting of the "increase" cells (issue to be risen)

**Comment by Cherryhz** [comment]
When conditional formatting the cells, 'criteria' and 'value' are needed. But in 'value', an int or a string is needed...not sure about a variable. I tried to change it as following, but it didn't work at Numbers.

self.worksheet.write('O6', 'decrease: ', self.format['Diff_decrease'])
        zero_value = self.worksheet.write('P6', 0, self.format['Diff_decrease'])
        self.worksheet.merge_range('O7:P7', 'increase:  5%', self.format['Diff_increase_small'])
        self.worksheet.merge_range('O8:P8', 'big increase:  10%', self.format['Diff_increase_big'])

        # conditional formatting the percentages columns
        conRange = 'K3:M113'
        self.worksheet.conditional_format(conRange, {'type':     'cell',
                                                     'criteria': '<',
                                                     'value':     zero_value,
                                                     'format':    self.format['Diff_decrease']})

**Comment by vvs-sev** [comment]
fixed when working on #25
