### ISSUE TITLE
amend header of Global (URT+SAAS) section of the release data sheet

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#29]
At the moment there's an empty row 98, and cells A98:C98 are merged. They should be un-merged, and headers be put there:
- C98: "entries";
- D98: "% of TrEMBL"

Merged cells A97:G97 should be un-merged, and smaller set of cells merged: A97:D97

**Comment by Cherryhz** [comment]
Resolved when solving #30
