### ISSUE TITLE
Normalise input file names

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#3]
When running the script specifying canonical input file names, it fails due to wrong characters in the sheet name. To try:
`python3 ./generateReleaseStatisticsDeviationReport.py --prevStat ./report-2018_01.txt --curStat ./report-2018_02.txt --outputFile 123.xls`
The problem is that it tries to use "./report-2018_01.txt" as sheet name and "/" is not allowed in sheet names. Please use a python function (mostly likely from "os.path" module) to cleanup input file names.

**Comment by Cherryhz** [comment]
import the os module; cleanup of the input file name is in a function called pathNameCleanUp.
