### ISSUE TITLE
make 1st section be found by an empty line rather than hard-coded 6th line of the report

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#6]
let's stipulate rules as follows:
* data file consists of set of sections separated by 1..N empty line(s);
* first section is header which we ignore for the moment;
* 2nd section is the data section which we begin to read.
* there can be 1..N empty lines before the header.

* for the purposes of this task "empty" means either zero-length OR whitespaces-only.

**Comment by Cherryhz** [comment]
In Class Report (readData/Report), add codes to break when the first empty line is found.
