### ISSUE TITLE
make numbers be stored as such in Excel cells

### ISSUE THREAD

**Issue by vvs-sev** [ebi-uniprot/aa.production#7]
currently numbers inserted into Excel cells are prepent with leading apostrophe.
This forces Excel to treat the numbers as a text, and does not allow numeric formatting as "thousands separator".
Please adjust cells to store numbers properly

**Comment by Cherryhz** [comment]
Have separate methods for writing headings and numbers. Issues solved and conditional formatting has showed colours according to the range indicated by legend.
