### ISSUE TITLE
Deviation sheet main headers to display the actual name of current and previous report names

### ISSUE THREAD

**Issue by Cherryhz** [ebi-uniprot/aa.production#9]
plan -add a function in xls_util/XlsUtil to generate main header names.

**Comment by Cherryhz** [comment]
Changes in XlsUtil.pathNameCleanUp so that the report name can be used in generating the main header.

**Comment by Cherryhz** [comment]
The main headers in the deviation sheet are now: 2018_01(current stat), 2017_12(previous stat), increase 2017_12 -->2018_01, abs, increase 2017_12 --> 2018_01, %.
TODO: merge the cells in the first row for each header. Note that, one can indicate cell contents and format in any of the merged cells.

**Comment by vvs-sev** [comment]
as we discussed, it may be better to do the merge after all the necessary content has been written into the upper leftmost cell of the merged range, and formatting applied to it.

**Comment by Cherryhz** [comment]
Use worksheet.merge_range() to write data directly into merged cells. Note the cell notation in XlsxWriter, A1 is equivalent to (0, 0) (row, col).
